name: build-test-deploy_frontend
on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  #manual trigger
  workflow_dispatch:
   
 
jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'

    - name: Install dependencies
      run: cd starter/frontend && npm ci

    - name: run lint
      run: cd starter/frontend && npm run lint  

  test:
    runs-on: ubuntu-latest
        
    steps:
      # Simulate a Deployment
      - name: running test interactively
        run: cd starter/frontend && npm test

  build:
    runs-on: ubuntu-latest
    needs: [linting,test]
    
    steps:
      # Simulate a Deployment
      - name: install dependencies
        run: cd starter/frontend && npm ci

      - name: run tests
        run: cd starter/frontend && npm run test